services:
  db:
    container_name: shortlink_db
    image: postgres:alpine
    ports:
      - "5431:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      - DB_SCHEME=postgresql+psycopg2
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=shortlink
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/pgdata
      - PGUSER=postgres
    volumes:
      - shortlink-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: shortlink_app
    ports:
      - "5005:8000"
    volumes:
      - .:/opt/app
    command: sh -cx "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    environment:
      - DB_HOST=db
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
volumes:
  shortlink-data: