"""link model added

Revision ID: ca2a9f9d810a
Revises: 
Create Date: 2023-06-27 14:26:39.780908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca2a9f9d810a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link_table',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('long_link', sa.String(), nullable=False),
    sa.Column('short_link', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('long_link'),
    sa.UniqueConstraint('short_link')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('link_table')
    # ### end Alembic commands ###
